# 工作流名称
name: 构建镜像并更新服务器

# 触发条件：推送到 main 分支时运行
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取代码
      - uses: actions/checkout@v4

      # 步骤2：登录到镜像仓库（如 GitHub Container Registry）
      - name: 登录到 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 步骤3：构建并推送新镜像（以 darwin-amd64 为例）
      - name: 构建并推送镜像
        run: |
          docker build -t ghcr.io/poterli/xense1:darwin-amd64 .
          docker push ghcr.io/poterli/xense1:darwin-amd64
          docker build -t ghcr.io/poterli/xense2:darwin-amd64 .
          docker push ghcr.io/poterli/xense2:darwin-amd64

      # 步骤4：触发远程服务器更新（就是你提到的这段代码）
      - name: 触发远程服务器更新容器
        run: |
          # 通过 SSH 登录服务器，执行 Watchtower 立即更新
          ssh user@your-server "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once arm64 darwin-amd64"
        # 注意：需要在 GitHub 仓库设置中配置 SSH 密钥（见下方说明）
    
